ruby_on_rail/config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  resources :products
  root to: 'static#search'
  get 'static/home'
  get 'static/search'
  get 'static/compare'

end

ruby_on_rail/app/models/product.rb
class Product < ActiveRecord::Base
end

ruby_on_rail/app/models/review.rb
class Review < ActiveRecord::Base
end

ruby_on_rail/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

ruby_on_rail/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    #@reviews = Review.where(model: @product.model)
    @reviews = Review.where(model: @product.model)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :model, :p_speed, :m_speed, :memory, :brand, :chip_brand, :price_amazon, :price_newegg, :price_bestbuy)
    end
end

ruby_on_rail/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
  end

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:model, :user_name, :content)
    end
end

ruby_on_rail/app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
    products = Product.all
    @memorys = products.uniq.pluck(:memory)
    @memorys = @memorys.reject { |m| m.nil? }.sort

    @brands = products.uniq.pluck(:brand)
    @brands = @brands.reject { |b| b.nil? }.sort

    @c_brands = products.uniq.pluck(:chip_brand)
    @c_brands = @c_brands.reject { |c| c.nil? }.sort
  end

  def search
    @memorys = Product.uniq.pluck(:memory)
    @memorys = @memorys.reject { |m| m.nil? }.sort

    @brands = Product.uniq.pluck(:brand) 
    @brands = @brands.reject { |b| b.nil? }.sort

    @c_brands = Product.uniq.pluck(:chip_brand)
    @c_brands = @c_brands.reject { |c| c.nil? }.sort

    @products = Product.all
    if params['filter'] != nil
      @products = @products.where(memory: params['filter']['mem']) unless params['filter']['mem'].count == 1
      @products = @products.where(brand: params['filter']['brand']) unless params['filter']['brand'].count == 1
      @products = @products.where(chip_brand: params['filter']['c_brand']) unless params['filter']['c_brand'].count == 1
    end
  end

  def compare
    @title = "TiTle"
  end
end

ruby_on_rail/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby_on_rail/app/helpers/products_helper.rb
module ProductsHelper
end

ruby_on_rail/app/helpers/reviews_helper.rb
module ReviewsHelper
end

ruby_on_rail/app/helpers/static_helper.rb
module StaticHelper
end

ruby_on_rail/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GraphicsCard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

ruby_on_rail/app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :p_speed %><br>
    <%= f.text_field :p_speed %>
  </div>
  <div class="field">
    <%= f.label :m_speed %><br>
    <%= f.text_field :m_speed %>
  </div>
  <div class="field">
    <%= f.label :memory %><br>
    <%= f.text_field :memory %>
  </div>
  <div class="field">
    <%= f.label :brand %><br>
    <%= f.text_field :brand %>
  </div>
  <div class="field">
    <%= f.label :chip_brand %><br>
    <%= f.text_field :chip_brand %>
  </div>
  <div class="field">
    <%= f.label :price_amazon %><br>
    <%= f.text_field :price_amazon %>
  </div>
  <div class="field">
    <%= f.label :price_newegg %><br>
    <%= f.text_field :price_newegg %>
  </div>
  <div class="field">
    <%= f.label :price_bestbuy %><br>
    <%= f.text_field :price_bestbuy %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ruby_on_rail/app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

ruby_on_rail/app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Model</th>
      <th>P speed</th>
      <th>M speed</th>
      <th>Memory</th>
      <th>Brand</th>
      <th>Chip brand</th>
      <th>Price amazon</th>
      <th>Price newegg</th>
      <th>Price bestbuy</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.title %></td>
        <td><%= product.model %></td>
        <td><%= product.p_speed %></td>
        <td><%= product.m_speed %></td>
        <td><%= product.memory %></td>
        <td><%= product.brand %></td>
        <td><%= product.chip_brand %></td>
        <td><%= product.price_amazon %></td>
        <td><%= product.price_newegg %></td>
        <td><%= product.price_bestbuy %></td>
        <td><%= link_to 'Show', product %></td></br>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

ruby_on_rail/app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

ruby_on_rail/app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<center>
  <h1><%= @product.title %></h1></br></br>
  <th><%= image_tag @product.image, size: "300x300" %></th>
</center></br></br>

<div class="container">
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th></th>
        <th>Amazon</th>
        <th>Bestbuy</th>
        <th>Newegg</th>
      </tr>
    </thead>

    <tbody>
      <th class="text-nowrap" scope="row">Price</th>
      <td class="red"><%= @product.price_amazon%></td>
      <td><%= @product.price_newegg %></td>
      <td><%= @product.price_bestbuy %></td>
    </tbody>
  </table>

  <div class="btn-group" role="group" aria-label="...">
    <%= link_to "Review", {controller: "products", action: "show", review: true}, class: "btn btn-default"%>
    <%= link_to "Detail", {controller: "products", action: "show"}, class: "btn btn-default"%>
  </div>
</div>

<div class="container">
  <% if params[:review] == nil %>
    <table class="table table-bordered table-striped">
      <tbody>
        <tr><th class="col-md-2" scope="row">Model Number</th>
          <td><%= @product.model %></td></tr>
        <tr><th class="col-md-2" scope="row">Brand</th>
          <td><%= @product.brand%></td></tr>
        <tr><th class="col-md-2" scope="row">Chip Brand</th>
          <td><%= @product.chip_brand%></td></tr>
        <tr><th class="col-md-2" scope="row">Memory Speed</th>
          <td><%= @product.m_speed%></td></tr>
        <tr><th class="col-md-2" scope="row">Memory Size</th>
          <td><%= @product.memory%></td></tr>
        <tr><th class="col-md-2" scope="row">Processor Speed</th>
          <td><%= @product.p_speed%></td></tr>
      </tbody>
    </table>

  <% else %>

    <table class="table table-bordered table-striped">
      <thead>
        <tr>
          <th>Number of review</th>
          <th>Rate</th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <td class="col-md-4" scope="row"><%= @product.num_reviews%></td>
          <td class="col-md-4" scope="row"><%= @product.rate%></td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="container">
    <table class="table table-bordered table-striped">
      <thead>
        <th class="col-md-2" scope="row">Most helpful review</th><th></th>
        <tr>
          <th class="col-md-2" scope="row">User</th>
          <th class="col-md-2" scope="row">Comment</th>
        </tr>
      </thead>

      <tbody>
        <% @reviews.each do |r|%>
          <tr>
            <td><%= r.user_name%></td>
            <td><%= r.content %></td>
          </tr>
        <% end %>
      </tbody>
    </table>


  <% end %>

  <%= link_to "Back", {controller: "static", action: "search", review: true} %>

</div>

ruby_on_rail/app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :user_name %><br>
    <%= f.text_field :user_name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ruby_on_rail/app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

ruby_on_rail/app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Model</th>
      <th>User name</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.model %></td>
        <td><%= review.user_name %></td>
        <td><%= review.content %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

ruby_on_rail/app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

ruby_on_rail/app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Model:</strong>
  <%= @review.model %>
</p>

<p>
  <strong>User name:</strong>
  <%= @review.user_name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @review.content %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>